### ISSUE TITLE
BTC Gold Core Wallet testnet configuration

### ISSUE THREAD

**Issue by virtualrobotix** [BTCGPU/BTCGPU#118]
Dear Friend,
congratulation for the testnet , it is up and work , i try to mine it and the miner work using  standard address.worker ... is already possible connect the BTC GOLD Core Wallet to tesnet ? It's already possible check the transaction and creation of Private Wallet Address ? 
Best
Rob

**Comment by h4x3rotab** [comment]
Not really. Only the first step of of testnet, pool integration, is done. The next step will be the p2p network and dnsseed. So it's not fully launched yet. I've prepared a participation guide for users / developers to join the public testnet and will release it when ready.

**Comment by jagottsicher** [comment]
The testnet works fine, but how you started mining? just a modified zcash miner?

**Comment by oliverw** [comment]
@h4x3rotab 

I second this. What's the situation with actual mining applications. Due to the requirement to encode the blockheight in the hashreserved field one would assume that miners such as Claymore need to be updated for this as well.

**Comment by L1ND44U** [comment]
Is there existing bitcoin gold core test, I need it to test it RPC daemon with pool. And what exactly was modified inside mining clients EWBF, claymore.

**Comment by evadogstar** [comment]
Any equihash miner will work...

**Comment by L1ND44U** [comment]
@evadogstar Then I don't see reason for forking miner clients, that means @StarbucksBG just renamed the official miner and put inside the bat file Gold pool and no modifications inside offical miner code.
I was playing with z-nomp but I do not see any major change in coin.json, but not able running because I have no test core to create rpc daemon and pool wallet....

**Comment by L1ND44U** [comment]
@starbucksBG Ok I see no difference just programming some pool tools. I made a couple of tests passed if anyone have wallet and rpc daemon running I need wallet address and daemon ip port or core to run test daemon in local.

**Comment by StarbuckBG** [comment]
First Of all it is StarbuckBG 

Second of all nheqminer needs modifications that I have already made as the other require to put correct flags to ensure that they will not stop. That way it is better for the people to start mining immediately not ready 10-15 minutes. 
I would kindly ask you to stop spamming our GitHub repo because that way you are making it hard for the people to find the information that they need. This is not constructive at all and I don’t know why you try to make everything negative.

**Comment by L1ND44U** [comment]
@starbuckBG hmm I made it different way and there is no need it modification in clients at all. I made couple of changes inside z-nomp and believe or not, but it is working much better than your secret mining client modification. Ok Mr.Developer if asking question is spaming or negative. Then bye I will not ask any technical details to help. You are just arrogant idiot. You are the best developer on the world and rest are just idiots, @Leto is bad, just you Bulgarian developer is the best....  Good bye and good luck Bitcoin Gold

**Comment by StarbuckBG** [comment]
Share this modification with the people like I have done. And there was nothing dev related in you previous posts. And I have never said anything bad personal for you, why you are calling me idiot? Based on what facts? And why you are racists about the fact I’m from Bulgaria. I’m proud of being Bulgarian, this is one of the countries with the best developers in the world and it is really small just 7M people, why you have problem with that. When you are so better than me and the other people, what better are you showing ? You don’t do anything constructive right now, just hating. Like the other faceless and nameless haters. 

And please respect me as I have respected you. I would never call you idiot or something else, because I don’t know you in person, I cannot judge based on assumptions and to call you in public like that. Show your face and name and stay behind your words, when you can say them like that :)

Just to ask again, when your version is so good, share it with the people :)

**Comment by L1ND44U** [comment]
@StarbuckBG i do not see anywhere, where you shared your changes of mining clients and z-nomp. You was so lazy to edit readme, what changes was done... I was the lead of developers and I work with best developers from Bulgaria, Romania, Russia, Czech, Germany. But they were professionals, not arrogant like you!!! 

Sorry i will not scam your forum or negative or hate someone. conversation is over. Bye

**Comment by dejandex** [comment]
@L1ND44U let's see your "couple of changes" or you're the idiot.

@StarbuckBG 👍

**Comment by L1ND44U** [comment]
@dejandex you will not see that changes I have done it I'm my free time. I do not need show off or do self presentation and undermine publicly colleagues like he have done to @leto. Ask the @starbuckbg to do magic. When your friend Starbucks was working in McDonald I was leading team of developers and most of us are already retired in young age having own companies. Sorry no pictures no personal information. I like to stay anonymous.... I do not need well paid job and telling everyone what I have done posting my pictures and projects in my past look at me mate look who I'm and what I have done for Bitcoin Gold more than anyone else....  bye I'm Idiot and I'm proud that I'm idiot bye lol 😂

**Comment by StarbuckBG** [comment]
I love when “the proficient dev leads” tell how much they do and understand, but never share their code ;) I like the way the actions expose the real truth, not the words. This is why I act, not just express empty words. 

I think that this issue can be Closed if there is nothing else to be asked on the real topic.

**Comment by L1ND44U** [comment]
@starbucksGB lol "I like the way the actions expose the real truth, not the words" speaking from your own experience. My Daughter remember how did you sent your Cvs arround the UK to get a job as senior c++ developer. Sorry mate copying code of others can do anyone, but find the real solution and make it just a few. That's why you are not working in UK or any prestige company and getting shit money in Bulgaria, that must be frustrating. Lol why i should give my code and solution to you after you call me racist, negative and spammer. I have not seen your proper documentation to changes you committed with z-nomp and clients and so many others asked for it. I made it my way even the cics to gold pool to handle that over cics layer... You are here arrogant wanker that dump his college @leto in public. If you will do it in my company you I will pick up my phone on Rottnest Island and tell my CEO to fire you on the spot... it's not just that you undermine Jonathan it's bad public presentation for Bitcoin Gold as the team... This issue cannot be closed there are missing answers that lay other people... Bye 👋

**Comment by jagottsicher** [comment]
@StarbuckBG do like Elso and "let it go." better we focus on constructive work. I am not in a position to contribute much more than being a beta tester, but better we don't waste time on non-developing discussions.

I will try an equihash-miner first to connect to the pool, but generally I would like to mine "solo", respectively start a pool. so I would like to have my own entity to mine to "at home". Is the client already ready for that?

**Comment by StarbuckBG** [comment]
I have never applied and looked for job in the UK. I have been working in the US, because I don’t like UK, it is cold, rainy and not so welcoming place. 
I would ask you not to lie about me. Moreover I do Swift and Objective C and I like them more than C++. I have never looked for a job as C++ developer. 
In 2013 I have been invited to start Engineering degree in Manchester, but I denied because I don’t like UK and because I’ve already got a job for US company before even to start my Bachelor. 

I end this here as all of your statements are not relevant and actually none of them is real. I will stop answer to you until you have the courage to show your name and face. I’m tired of nameless haters that can only hate here without showing their name, because they will not say a word if we were face to face.

**Comment by StarbuckBG** [comment]
You can run my version of z-mono at your private server, it will word out of the box. 
If you need help you can contact me in Slack, the group of BTG - my nick there - Martin Kuvandzhiev

**Comment by jagottsicher** [comment]
@StarbuckBG do like Elso and "let it go." better we focus on constructive work. I am not in a position to contribute much more than being a beta tester, but better we don't waste time on non-developing discussions.

I will try an equihash-miner first to connect to the pool, but generally I would like to mine "solo", respectively start a pool. so I would like to have my own entity to mine to "at home". Is the client already ready for that?

**Comment by L1ND44U** [comment]
@starbuckGB that is some paranoia , every one hates you... I like @h4x3rotab and @leto the first I named I know and want stay anonymous same as the most famous coders want stay anonymous and working coding hard and never undermine anyone. Very humble and smart and not doing here self presentation like you.... And I like Jonathan and his wife. You are very arrogant Martin so far you have not done job, code properly... bye looser

**Comment by evadogstar** [comment]
Conclusion: 
@L1ND44U better to share something and help new community. it's github and open source
@StarbuckBG I have some hopes on this project. Hope you (team) know what you do. And always work more with community and give more information as @L1ND44U noticed (at readme, blogs and at github)

**Comment by jagottsicher** [comment]
I like patotoe stew and i don't like people who ate too much garlic in oil.
Now after a nice smalltalk and exchange of our likes and dislikes we focus again on work.

**Comment by evadogstar** [comment]
@jagottsicher  Please, before mainnet start give as the simple way to generate G address with html&js offline wallet

**Comment by bilbobits** [comment]
https://github.com/BTCGPU/BTCGPU/issues/135

How to make a "G" address, was posted earlier, but the GODS deleted the post by sending it to the 'done bucket', I suggest you read there, as the good stuff always gets dumped/deleted by the gods ( btcgpu devs)

**Comment by D3m0nKingx** [comment]
@bilbobits you can't read? #135 only stated G addresses can't be used on testnet, there was no instruction how to generate them. those are for main net addressing scheme only... and everybody who know's anybody understands to generate addresses is just by running the `getnewaddress` or `getaccountaddress "account"` If you want to generate addresses with a specific scheme, you need to modify the code itself.

**Comment by h4x3rotab** [comment]
> How to make a "G" address, was posted earlier, but the GODS deleted the post by sending it to the 'done bucket', I suggest you read there, as the good stuff always gets dumped/deleted by the gods ( btcgpu devs)

I think you misunderstood what a GitHub issue is for. It's used to solve development related issue and track the process. It's not a Q&A section or a forum. You can search for solutions but there's no need to keep them in the opening list.
