### ISSUE TITLE
when mainnet?

### ISSUE THREAD

**Issue by krtschmr** [BTCGPU/BTCGPU#120]
why mine on testnet?

**Comment by andre-amorim** [comment]
because all crazy development ideas occurs on testnet. Try to see it as "The Labs" area.

**Comment by WarSoar** [comment]
You really have to ask? TEST... look it up.

**Comment by TheComputerGenie** [comment]
The fact that this question even gets asked is **everything** that is wrong with crypto today.

**Comment by krtschmr** [comment]
@TheComputerGenie the fact that there is just another scam-fork is also showing what's wrong with crypto, ya?

BTCG fixes zero problems of bitcoin. true story.

**Comment by TheComputerGenie** [comment]
@krtschmr You don't know what it does/doesn't fix, because you (personally) don't even know what/why it is! If you really have to ask why a beta isn't a full release, they you have no basis to decide what it "fixes" or what the "problems" even are.
I'm not even sure I'm a fan of the project; that fact, alone, should tell you how wrong you are and how uneducated you are about crypto, programming, and the entire sphere in which the rest of us reside.

**Comment by krtschmr** [comment]
@TheComputerGenie if you follow my issues on BTCG you'll see that i *wanted to contribute hashingpower* but somehow got slapped in my face by the answers. 

i don't ask **why** mine on testnet, for what's the reason. i simply ask *why mine on testnet*  for pointing out that mainnet is heavy delayed.

**Comment by h4x3rotab** [comment]
We will officially announce it when it’s ready. We need a few days to fully prepare for the mainnet. Closing this issue because it’s not related to development. Please join our slack channel and ask us directly.
