### ISSUE TITLE
Warning: unknown new rules activated (versionbit 28)

### ISSUE THREAD

**Issue by jagottsicher** [BTCGPU/BTCGPU#127]
-getinfo throws the error "Warning: unknown new rules activated (versionbit 28)" while on testnet. 

>  "version": 150001,
>   "protocolversion": 70016,
>   "walletversion": 139900,
>   "balance": 0.00000000,
>   "blocks": 1210470,
>   "timeoffset": 0,
>   "connections": 8,
>   "proxy": "",
>   "difficulty": 27325.75121241282,
>   "testnet": true,
>   "keypoololdest": 1508480357,
>   "keypoolsize": 2000,
>   "paytxfee": 0.00000000,
>   "relayfee": 0.00001000,
>   "errors": "Warning: unknown new rules activated (versionbit 28)"

Normal?

**Comment by bilbobits** [comment]
Below is mine, ... looks fine to me, using the 'current' right now "get pull" of this github/btcgpu

Why is your's different?? I can only think you need to go to the folder and do a 'git pull' and re-build, I will attach a build.sh script,  I think its important because people can waste much time trying to 'build' this damn source, that really wasn't tested much, it appears that much 'dev' is/was being done on 'mac'.

 src/bgold-cli getinfo
{
  "deprecation-warning": "WARNING: getinfo is deprecated and will be fully removed in 0.16. Projects should transition to using getblockchaininfo, getnetworkinfo, and getwalletinfo before upgrading to 0.16",
  "version": 150001,
  "protocolversion": 70016,
  "walletversion": 139900,
  "balance": 0.00000000,
  "blocks": 1210459,
  "timeoffset": 0,
  "connections": 1,
  "proxy": "",
  "difficulty": 27344.27923900051,
  "testnet": true,
  "keypoololdest": 1509540900,
  "keypoolsize": 2000,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": "This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"
}

**Comment by bilbobits** [comment]
More looking at your? R U sure you have..

1.) started from a VIRGIN blockchain, this bitch btcgpu doesn't support the old,

2.) have you -reindex your complete -testnet chain?

I have seen this 'message' before but it was 2-3 days ago, ... thus IMHO you need to do a complete rebuild, ... as you can see I'm not getting this message, here is my build.

/home/Mining/btcgpu $ cat build.sh

****
./autogen.sh

./configure CPPFLAGS="-I/usr/local/BerkeleyDB.4.8/include -O2" LDFLAGS="-L/usr/local/BerkeleyDB.4.8/lib"


make -j 1 
****

U must explicit tell about the DB, otherwise your wallet will not build, and you will get a ton of compile errors, and messages that tell you to disable the wallet.

**Comment by bilbobits** [comment]
Did see this a few times again today, I think I mentioned to you I seen before, 

chain-active-update, line 2027 validation.cpp

        for (int bit = 0; bit < VERSIONBITS_NUM_BITS; bit++) {
            WarningBitsConditionChecker checker(bit);
            ThresholdState state = checker.GetStateFor(pindex, chainParams.GetConsensus(), warningcache[bit]);
            if (state == THRESHOLD_ACTIVE || state == THRESHOLD_LOCKED_IN) {
                **const std::string strWarning = strprintf(_("Warning: unknown new rules activated (versionbit %i)"), bit);**
                if (state == THRESHOLD_ACTIVE) {
                    DoWarning(strWarning);
                } else {
                    warningMessages.push_back(strWarning);
                }


It's validation.cpp, a state problem, doesn't happen that often, but every once in awhile this 'error' pop's up in the error state of getinfo, getmininginfo, ...

I'm sure our dev will looking into this seems to be more of 'warning' not much of a show stopper.

**Comment by jagottsicher** [comment]
I compiled already severeal times. usually with 
`./configure CPPFLAGS="-I${BDB_PREFIX}/include/ -O2" LDFLAGS="-L${BDB_PREFIX}/lib/" --without-gui`

it always worked fine. 
Due to the fact I run also severeal full nodes I compiled the DB8 on my own on my development machine:

> 
> $ tar -xvf db-4.8.30.NC.tar.gz
> $ cd db-4.8.30.NC/build_unix
> $ mkdir -p build
> $ BDB_PREFIX=$(pwd)/build
> $ ../dist/configure --disable-shared --enable-cxx --with-pic --prefix=$BDB_PREFIX
> $ make install
> $ cd ../..

Using the same for bitcoin.

I will rebuild the testnet now. that sounds reasonable

**Comment by jagottsicher** [comment]
unfortunately ` "errors": "Warning: unknown new rules activated (versionbit 28)"` came up again after some time running the node in the testnet.
my debug log is spammed with `2017-11-04 12:15:08 UpdateTip: new best=0000000cc617f33c6aedb9171e58793d648e6e6c736d4584e4c52d1330251594 height=1210618 version=0x20000000 log2_work=69.624455 tx=15593152 date='2017-11-04 12:15:02' progress=1.000000 cache=22.4MiB(48825txo)
` only. 

anybody knows something about why the "new rules warning" comes up? it seems to be not a problem for the client to deal with.

**Comment by bilbobits** [comment]
As the code above shows its just a warning, the dev's have to decide to support it, or add an exception to the warn state

yes, completely random, probably useful to add an existing debug to this state, so that we could know more about the transaction/block being processed that caused this state, now nothing is known

it would be easy to add an additional sprintf() to the warn buffer to include 'getinfo' or some data like btc-version, could be a newer client, or perhaps a rogue copy of btcgpu injecting nonsense into the testnet

**Comment by bilbobits** [comment]
Seems odd the DEV's have ignored this?? Right??

It does show up on the pool.gold banner, not good for end users to see a message that the system is in error, will lead to much confidence failure later if this 'warn-error' is not addressed, silence, fixed, and./or resolved.

**Comment by StarbuckBG** [comment]
@bilbobits 
Again, stop the spam. 
This is a pointless warning we could silence.

This is 17 ticket submitted by you in the last 3 days.
Use Slack chat.

**Comment by bilbobits** [comment]
wow why don't u remove this then? the OP asked this question days ago, and finally u show up and say what I have said all along, ... bravo

set this as closed if you intend to resolve

**Comment by h4x3rotab** [comment]
If you run Bitcoin Core you will receive the same warning. No need to worry.
