### ISSUE TITLE
How can I sync BTG mainnet, before "Error: mainnet is not ready for launch."

### ISSUE THREAD

**Issue by Airead** [BTCGPU/BTCGPU#159]
How can I sync BTG mainnet, before "Error: mainnet is not ready for launch."
```
$ ./bgoldd
Error: mainnet is not ready for launch.
```

It's **too later** to sync mainnet blockchain after mainnet lauch at "12th November 2017 (19:00 UTC)".

**Comment by OleksandrBlack** [comment]
git pull origin testnet2

mainnet network is not ready

**Comment by Airead** [comment]
Can I migration bitcoin blockchain data to BTG?  And how to do?

If migration is possible, I will save a lot time to sync mainnet from block 1 to snapshot.

**Comment by h4x3rotab** [comment]
We are still working on a few changes. When all the necessary changes are ready, we will allow mainnet mode.

The Bitcoin datadir is not compatible with BTG. So you can't copy it directly. I've added a command line flag called `-bootstrap`. In this mode the BTG client can connect to Bitcoin p2p network and download the blockchain history before the fork height. It's a little tricky to use this flag because you still need to add some Bitcoin node to the client. Otherwise it will not get any peers.

**Comment by Airead** [comment]
@h4x3rotab Thank you! I think -bootstrap is my wanted. But an error occurred while using -bootstrap.
```
/bgoldd -bootstrap
Error: mainnet is not ready for launch.
```

**Comment by Ayms** [comment]
@h4x3rotab it's time and it will be fair now/not risky for you to allow people to sync at least until block 491407 before the launch

**Comment by savskii** [comment]
yea were all waiting so sync from before but don't look like its gonna happen

**Comment by Thecreator1** [comment]
I am on a 'narrow' 20 Mbit ADSL it will take many days to download the blocks up to the fork... 
So i just decided many cpu no vote.

**Comment by Raulo** [comment]
You can remove the lock and recompile. 

This line is in src//bitcoind.cpp is responsible for the check. 

if (chain == CBaseChainParams::MAIN)
                throw std::runtime_error("mainnet is not ready for launch.");

If you remove it or comment it out, the code will start to download the Bitcoin blockchain. 

I'm pretty sure that it will take days if not more before the exchanges are ready.

**Comment by ric77barradas** [comment]
https://github.com/BTCGPU/BTCGPU/pull/162/commits/ecb418a3d0d30568a01bae0f28fce9ebb8279968

this should solve it

**Comment by Airead** [comment]
@Raulo Thank you. I remove it and it can run almost normal, but 0 addresses found from DNS seeds. Any suggestion?

**Comment by Raulo** [comment]
@Airead, maybe the peer discovery mechanism is not yet turned on. Connect to a known Bitcoin server, best your own. If you don't have one, there are many available (in this case better to connect to a few to easy the traffic) https://bitnodes.earn.com/. Use -connect=ipnumber:port.

**Comment by Airead** [comment]
@Raulo Thank you very much! I'm syncing.

**Comment by oliverw** [comment]
@Raulo Are you suggesting to sync against the BTC main chain and switch to the BTG chain later on?

**Comment by jagottsicher** [comment]
@Raulo no ida, but think that's not fully thought through, cause the fork already happend 25. October and you sync now with the whole chain, so also with ll blocks from 25th octobert to today. eventually you have to reindex anyway, or? so, if you don't have a snapshot of the chain at 25 october your screwed with syncing.

**Comment by oliverw** [comment]
By the way. Does anyone else trouble to mine a single block on testnet?

**Comment by Raulo** [comment]
@jagottsicher,

You download blocks up to 491406 and then wait for the rest (the code will stop downloading after this block) when they go live. They are premined so there is no way to get them otherwise. I don't think you'll have to reindex anything (except maybe for the wallet but it does not take long) because blocks up to 491406 would not change.

**Comment by jagottsicher** [comment]
didnt know they hardcoded that. thank for the info.

**Comment by jagottsicher** [comment]
@oliverw I didn't but only ran the miner temporarly

**Comment by oliverw** [comment]
@jagottsicher So you've mined some blocks on testnet?

**Comment by oliverw** [comment]
Difficulty seems to be incredibly high for a testnet. Currently at 1210954

**Comment by savskii** [comment]
guys, is this a MUST ? do we have to sync before and upto block 491407? or do we just wait till main net then sync from block 491407 to now?

**Comment by jagottsicher** [comment]
@oliverw nope. i mined on the testnet, but never found a block. did you?
and the difficulty is mybe that high, because they're mining with lots of hardware and adjust the difficulty after each block. so with some GPU's you're quickly behind. :-)

**Comment by oliverw** [comment]
@jagottsicher Pool code appears to be working. Yet unable to mine a block due to network diff.

**Comment by jagottsicher** [comment]
I forked from & set up [https://github.com/poolgold/z-nomp-bitcoin-gold](https://github.com/poolgold/z-nomp-bitcoin-gold) and pointed the underlaying node to the testnet. everything works smoothly after some settings and debugging (lots of confusion, because it is written mainly for zcash). tomorrow I will switch to the main net, but am afraid of never been able o mine a block without help. guess the diff will be similar like the testnet, or even higher.
