### ISSUE TITLE
No connections

### ISSUE THREAD

**Issue by Grix** [BTCGPU/BTCGPU#172]
The client doesn't find any nodes to connect to, just says "0 active connections to the bitcoin network".

**Comment by EagleTM** [comment]
Try addnode=109.201.133.93:8338  
addnode=178.63.11.246:8338

**Comment by Grix** [comment]
Thanks, it worked adding the nodes manually.

**Comment by hubdr** [comment]
@EagleTM may I ask where you got those 2 nodes?

**Comment by liuxurong** [comment]
@EagleTM 可以用。

**Comment by deke997** [comment]
@EagleTM What are these nodes?

**Comment by liuxurong** [comment]
同步时间太长，我想请问，我已经同步好了比特币节点文件，在#block499407之前它们是一样的，它们可以不可以在本地复制一份重用？

I would like to ask that I have synchronized the bitcoin core, which are the same before block#499407. Can they replicate a reuse locally?

**Comment by Crypto-Lord** [comment]
@hubdr @deke997 
Go to Setting ->Options-> Open Configuration File (Opens notepad)

Type in:
addnode=109.201.133.93:8338
addnode=178.63.11.246:8338

Then save & restart wallet

**Comment by dejandex** [comment]
How to add them what.conf ?

**Comment by DarthJahus** [comment]
Excellant question, @liuxurong. Instead of syncing the whole blockchain again, can we use the blockchain from Bitcoin?

**Comment by dejandex** [comment]
bitcoin.conf 

Thanks :)

**Comment by EagleTM** [comment]
@hubdr  #bitcoingold on freenode

**Comment by EagleTM** [comment]
@deke997  nodes to sync to with bgoldd

**Comment by srmo** [comment]
Ok, added those two nodes. I now have 1 connected node and a downstream of ~14kB/s 
Will this move up or do you have better seeds?

**Comment by EagleTM** [comment]
addnode=109.201.133.93:8338
addnode=178.63.11.246:8338
addnode=
addnode=
addnode=

   "addr": "109.201.133.93:8338",
    "addr": "",
    "addrlocal": "139.59.151.13:8338",
    "addrbind": "139.59.151.13:8338",
    "addrlocal": "139.59.151.13:8338",
    "addrbind": "139.59.151.13:8338",
    "addrlocal": "139.59.151.13:8338",
    "addrbind": "139.59.151.13:8338",
    "addr": "172.104.157.62:8338",
    "addrlocal": "139.59.151.13:8338",
    "addrbind": "139.59.151.13:8338",

**Comment by evadogstar** [comment]
Is it pre-mine now or I can start mining?

**Comment by srmo** [comment]
@EagleTM  why do you use duplicate bind/local commands? Isn't this supposed to be just called once (per local interface)? PS: just learning the bitcoin.conf.
From what I see you also use only those two seeds or should I use our local address as additional seed?

**Comment by srmo** [comment]
Shouldn't there be a peer exchange?

**Comment by ICOBOXER** [comment]
added nodes, still not updating blocks

**Comment by srmo** [comment]
@ICOBOXER does it update "header data"? That's the first step

**Comment by ICOBOXER** [comment]
Not sure, How can I see that?

root@vmi139025:~/BTCGPU/src# ./bgold-cli getinfo
{
  "deprecation-warning": "WARNING: getinfo is deprecated and will be fully removed in 0.16. Projects should transition to using getblockchaininfo, getnetworkinfo, and getwalletinfo before upgrading to 0.16",
  "version": 150001,
  "protocolversion": 70016,
  "walletversion": 139900,
  "balance": 0.00000000,
  "blocks": 0,
  "timeoffset": 0,
  "connections": 10,
  "proxy": "",
  "difficulty": 1,
  "testnet": false,
  "keypoololdest": 1510516427,
  "keypoolsize": 2000,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": "This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"

**Comment by jagottsicher** [comment]
please see your log in `/.bitcoingold/debug.log`

**Comment by ICOBOXER** [comment]
It was a closed port issue

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by oliverw** [comment]
Anyone else got some working node addresses?

**Comment by DarthJahus** [comment]
Someone published a list on the [Telegram group](https://t.me/BTCGoldChat), Changed it to `bitcoin.conf` format:

[BTG-Nodes.txt](https://github.com/BTCGPU/BTCGPU/files/1466673/BTG-Nodes.txt)

**Comment by oliverw** [comment]
Thanks for sharing @DarthJahus. Could you post this to https://github.com/BTCGPU/BTCGPU/issues/178#issuecomment-343868143 as well?

**Comment by khelle** [comment]
So, after approximately 48H of running BTG node I still have 0 connections and no blockchain downloaded. Any fix for this yet?

**Comment by DarthJahus** [comment]
Can someone **unable to sync** on Windows (x64) try this?

1. Download [this build](https://mega.nz/#F!9MlUXRbS!s8XV9JUH07qAW8eKp0fxHg)
2. Remove all from `%AppData%\BitcoinGold` except `wallet.dat` (unless you want to remove your wallet)
3. Move `bitcoin.conf` file to `%AppData%\BitcoinGold`
4. Run the wallet and go to Help > Debug window and see if the connections are working

On Linux, you need to do steps **2**, **3** and **4**. The `bitcoin.conf` file is available in the link provided in step **1**.

I'm unsure of the equivalent of `%AppData%\BitcoinGold` on Linux but it may be `.config/BitcoinGold`.

----

Originally posted [here](https://github.com/BTCGPU/BTCGPU/issues/178#issuecomment-344577808).

**Comment by dexX7** [comment]
I recommend not to download any binaries ever. They are likely infected!

**Comment by srmo** [comment]
Agreed. @DarthJahus, why dont you provide a community verifiable patch?

**Comment by DarthJahus** [comment]
You don't have to get my binaries. I tried to provide an idiot-proof step by step guide, since people who may read this don't always know what they do. But if you know, download binaries from the official release and get my `bitcoin.conf` file and follow the other steps [here](https://github.com/BTCGPU/BTCGPU/issues/172#issuecomment-344605344). Or just create your own conf file and put `addnode=btg.surpnova.cc` as the only line inside, remove all the other data (files and folder) in `%AppData%\BitcoinGold` but **keep your wallet** and try to sync. **Suprnova** node can handle you and all the miners on it (more than 120 MSol/s there actually).

By signing the binaries with my Keybase key, I reveal my identity. Is there any other trusty way to release something? Considering you may build the code in this repo without reviewing it and without knowing the real identity of the main dev… But well. @srmo, how can I provide a **verifiable** patch?

**Comment by srmo** [comment]
If we don't need your binary, why advertise it?

The thing is that you just don't have the reputation to be trusted in comparison to well known projects that can be hold accountable for mischief. 
And what is a key proving? I can create keypairs too, that doesn't make me trustworthy if no one else has verified my identity (ever herad of crypto parties?)

And putting out such an unverified binary in the midst of warning mails about scams and infected binaries is, well, bold.

If I build this code here, I can expect at least 100 other people building this code too and at least 2+ independent people to have taken a look on it. Usually, FLOSS software establishes trust by just giving you the opportunity to verify the code. Just putting out a binary does nothing.

**Comment by h4x3rotab** [comment]
Please only run the official prebuilt binaries or build your own binaries (better). BTW, you can download the bootstrap.dat file from the magnet link on the official download page.

**Comment by DarthJahus** [comment]
> And putting out such an unverified binary in the midst of warning mails about scams and infected binaries is, well, bold.

Made the binary public on Slack _before_ the team releases the official binary. Published it here because the steps I gave work with these binaries, how can I know if something has changed in the "official" release? I provided an idiot-proof guide to help people connect to the network at a time when almost no one succeeded to sync. Wanted to help. If you don't like it, don't use it. I engaged my real-life identity, if you don't understand Keybase, it's your problem. If you don't trust me, it's also your problem. Actually, I provided more identity proofs than your dear "official" devs.

**Comment by h4x3rotab** [comment]
I didn’t mean to offend but just bring up some common sense to all the readers. But anyway, it’s always better audit the code and compile your own client. Soon we will release binaries produced by Gitain, which can be used to verify the binaries are really not manipulated.

**Comment by srmo** [comment]
Just for the sake of it. You have to be paranoid. On the net and even more so when it comes to money on the net. If you think I'm too paranoid, well, think again: how do you prove that it is actually "you" that is linked as social media identity? You can't. That's the name of the game in the internet. Claiming otherwise is naive. Stealing accounts, setting up fake accounts. People did that for way less than what is at stake for some people in the crypto market. As h4x3rotab put it, I'm not meaning to offend you, just giving my paranoid advice. You are right, I have no way to prove that the dev team is more trustworthy than your keybase identity. But I don't think that this renders my thoughts moot.
