### ISSUE TITLE
Testnet

### ISSUE THREAD

**Issue by oliverw** [BTCGPU/BTCGPU#189]
Is there currently any working testnet?

**Comment by Airead** [comment]
I want to test something on testnet, any testnet working?

**Comment by 5dao** [comment]
it big data file ,the best way is mainnet

**Comment by oliverw** [comment]
@5dao Yeah sure, try solo mining on mainnet for testing pool code.

**Comment by litwi1rm** [comment]
I've also been inquiring about testnet. I've been able to connect to a dozen peers on testnet, but it's always at the same block and shows 10MSol/s net hash.

**Comment by r0bocharov** [comment]
I'm interested in testnet too.

**Comment by h4x3rotab** [comment]
Testnet is not working currently because the difficulty reset logic is not implemented. As a result, the difficulty of testnet remains so high that nobody can mine a single block. We are going to reset the testnet again with new diff adjustment algorithm and diff reset logic (for testnet). I will open another issue to track the progress of the new testnet.
