### ISSUE TITLE
Support multiple PoW

### ISSUE THREAD

**Issue by ghost** [BTCGPU/BTCGPU#19]
Same chain, different PoW on each block - each one with different difficulty depending how often it is used (are there ASIC out there), hijack 1 byte from e.g. version to state which hashing algorithm use to verify. It could also allow some support from desperate SHA256 miners, before GPU pools will kick in.

**Comment by h4x3rotab** [comment]
Good suggestion. Multiple PoW also makes PoW switching easier. I'd like to explore it in the next milestone.

**Comment by Grimm2017** [comment]
Interesting concept.  Are there any other coins that have a similar thing?

**Comment by krtschmr** [comment]
@Grimm2017 and if the price is not right the difficulty is very low, so more coins for everybody, right? Either this project will die within 2 weeks or the whole *whattomine* thing will even out each other, so it wont really matter what you mine,  longterm we all "do the same".

Onliest issue is that equihash just attracts Nvidia GPUs and most hashingpower in ETH and Cryptonight is AMD based... They simply won't switch. If i/we switch our AMD Farm to ZCash i'll might hav -40% return daily. Same for this coin. Unless the price is soooo high. But if it is, then all ZCash power jumps straight over, equalizing things anyways.
I can only contribute small since 94% of my hashingpower is AMD based.... Big issue i think. Too late anyways :)

**Comment by just-an-dev** [comment]
@Grimm2017 look myriadcoin :)

**Comment by omar-hesham** [comment]
Please do not do that.

**Comment by krtschmr** [comment]
omar-hesham why not?
