### ISSUE TITLE
16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation) (code -26)

### ISSUE THREAD

**Issue by tadejgasparovic** [BTCGPU/BTCGPU#214]
I've had some Bitcoins on a multisig address when the fork happened and now I'm trying to claim them. I have the required private keys to sign the transaction, but when I try to broadcast it to the network I get the following error:

**16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation) (code -26)**

I tried verifying the signed transaction on [BTGWallet.online](btgwallet.online/#verify) and everything seems to be fine. I've also read a lot of discussions where people were having the same issue with other clients such as Electrum Cash and Bitcoin Classic. So I'm guessing there's a problem with this client as well. I would appreciate it if this could be resolved ASAP.

Signed raw transaction:
`0200000001929293fa4d28de75e69f4afd1c734fbbfb4594bcc2f9adfce9cde7d903e9bbd202000000fdfd0000483045022100c45dd4e0c1eb8dae508efcbcc02f965c3cd9ca2abcf62448f74354ce1fc4321b02203bda025df4251b53194a4bf49095591382f331017bdc36e1edbd9eedc9cfda4941473044022048bdcd91f900017555e2ceb734871ae7697c565775e2cd5bcc438e783f8ea10f0220250a9e68d85a4595935231122c1679eab9d898f4682d9a6ebdcf036d18250279414c695221020b37b02492a6ccfb562c21b45e5f23c3142eb5c19030f8ea3b15b255b6443f312102a0c393c074ec813879a244c9e1a34b2d6df451392ad4ccf0c0dc15f45a9c5c5a2103731655ac4610f7af373ae849d4f45c9745f8a1fc613715c8d7f486bda3b1c90153aeffffffff01fb7e4014000000001976a91462b34e22fd01719db8bdd140f65685180eaba3ba88ac00000000`

**Comment by h4x3rotab** [comment]
AFAIK the signing feature of BTGWallet.online is broken. It signs the transaction in the original Bitcoin way. So basically it triggered the replay protection of BTG.

Before it's updated, you can always try to sign the multi-sig tx with Bitcoin Gold core client though much more tedious.

Here is an example: https://bitcoin.org/en/developer-examples#p2sh-multisig
An simpler version by Gavin: https://gist.github.com/gavinandresen/3966071

Note that due to the replay protection logic, you need to specify the `amount` field of each input UTXO when signing the transaction. Both examples didn't specify that.

**Comment by tadejgasparovic** [comment]
@h4x3rotab Thanks! I was using Bitcoin Gold Core to sign the transactions from the beginning, but I didn't know I had to include the `amount` field. I've signed the transaction again with the `amount` field included and the transaction sent successfully!
