### ISSUE TITLE
TX Transaction dissapear!! Please help me.

### ISSUE THREAD

**Issue by dominiaz** [BTCGPU/BTCGPU#223]
I was mined 1 BTG and everything was ok until today. Today TX Transaction dissapear !!

https://btgexp.com/tx/187a29750110ff352a99dfddcc22a59c0efa853d68eaae6c06d677c2afdc9cee

What is going on?

**Comment by evadogstar** [comment]
Can you do something with it? Yes, warn all ppl about that issue. This scamcoin must be closed. We should not wait until exchanges will open DEPOSIT operations and thieves will sell their stolen wealth and cheer. It can not be tolerated

**Comment by dominiaz** [comment]
Everything is ok now. Transaction registered on btgexp after 30min. Looks like blockchain doesnt fully sync.

Please close.

**Comment by h4x3rotab** [comment]
Should I delete @evadogstar's replies? He is abusing GitHub issue for non-development purpose.

**Comment by dominiaz** [comment]
yes

2017-11-21 19:19 GMT+01:00 h4x3rotab <notifications@github.com>:

**Comment by Thecreator1** [comment]
Of course you want to have the negative words removed because they make you look bad.
Evadogstar is using GitHub for after-development purpose.
He is not telling lies, the miner funds were lost.
And we haven't seen anything back as of yet.
So please don't act like an asshole.
Did you know that after i moved away from the pool.gold they started to attack my server by brute force ?
Luckily they are not able to crack my security.
I know who you are...

**Comment by dominiaz** [comment]
Guys why are you spamming my post? Make your own post with your own problems.

My problem was solved automatically. For me almost everything works as a charm.

**Comment by Thecreator1** [comment]
Because they are trying to hide the truth.
And you agree on this.
