### ISSUE TITLE
Peer Connections Misbehaving, Receiving Bad Headers, Client will not Sync

### ISSUE THREAD

**Issue by D3m0nKingx** [BTCGPU/BTCGPU#28]
I've downloaded the bitcoin blockchain: https://getbitcoinblockchain.com/

Then when starting the client on the splash screen stated it was upgrading the UTXO, which completed and the wallet opened, showing the syncing process. However the connections never stay constant, and a lot of peers are banned. and no synchronization seems to be occurring (5 weeks behind), ran this for a few hours, and it never progressed past the block it's "stuck" at.

Debug log:

https://gist.github.com/D3m0nKingx/26dfb18dfa89c6d3f910ede006322e20

**Comment by h4x3rotab** [comment]
Hi @D3m0nKingx, this is expected behavior. The code change of the client is not finished yet so there's no way to run it. Feel free to check the current pull requests.

The reason why it stuck at a certain block height is due to the fork height defined by "params.BTGHeight". When the client reaches the fork block height, it will enable new consensus rule thus rejects all Bitcoin nodes. Also, the fork height will be changed to some block that will be mined in Oct 25 later.

So, don't worry. We will announce when the client and the testnet is ready.

**Comment by D3m0nKingx** [comment]
Thank you, closing.
