### ISSUE TITLE
Testnet: 'Bitcoin is downloading blocks...'

### ISSUE THREAD

**Issue by toffick** [BTCGPU/BTCGPU#363]
When I run the `getblocktemplate` rpc call it returns the message:
Bitcoin is downloading blocks…
What i do wrong?

**Comment by h4x3rotab** [comment]
It's probably due to lack of miner. When a full node can't get a block within 24 hr, which is common in a testnet, it will stay in "initial block download" mode. You can check the latest block at test-explorer.bitcoingold.org. If there's no recent block, you can specify a larger "-maxtipage" (e.g. 10 days) in second.

**Comment by toffick** [comment]
at the moment of writing the issue the node was already fully synchronized, but didn't receive any mined block. later i started GPU miner, it solved  new block, BTG node received it and later I was able to call getblocktemplate with payload without any errors.

**Comment by h4x3rotab** [comment]
I believe it’s the case. Closing now
