### ISSUE TITLE
Vulnerability report (1) : Tab nabbing

### ISSUE THREAD

**Issue by raza5402** [BTCGPU/BTCGPU#376]
Hi team,

I am security researcher and this time i founded this vulnerability in you website : https://allbit.com/
 
Vulnerability report:  Tab nabbing

Issue lies Here :

<a target="_blank" href="https://www.facebook.com/bitcoingoldofficial/">

Here i can see you are using target=_blank and no more rel tag.
Here , target=_blank means it will open in another new tab but due to tab nabbing it can change parent tab as well .So as per security principal don't trust much on 3rd party and be at your safe side.

FIX & MITIGATION :
To mitigate this issue we need to use rel="nofollow noopener noreferrer" as follows: 

<a rel="nofollow noopener noreferrer"
![bitcoingold](https://user-images.githubusercontent.com/49895674/57968566-24cff180-7921-11e9-8b8e-ed80280f6757.png)
 target="_blank" href="https://www.facebook.com/bitcoingoldofficial/">

Refrence:

https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

I Hope you will fix this issue as soon as possible. Looking forward to hear from you. Thank You

Sincerely,
Ali Raza

Proof of concept:

**Comment by h4x3rotab** [comment]
Thanks for reporting. I've redirect the issue to our SysOps team. This repo is mainly use for reporting bugs regarding the Bitcoin Gold network and the Core Node. Problems related to the official website can be reported to our [Responsible Disclosure Program](https://github.com/BTCGPU/dev/blob/master/responsible-disclosure.md).

**Comment by raza5402** [comment]
Please let me know have you accepted my report or not?

**Comment by MentalNomad** [comment]
Your report regarded a vulnerability on "https://allbit.com/" - you should report this to them. They are unrelated to the Bitcoin Gold project.

This repo has no relationship to any website: it is only for the Bitcoin Gold Core Wallet software.

**Comment by raza5402** [comment]
This report is for bitcoingold, by mistaken I have written anothr domain.
This report is of bitcoin gold kindly examine it

**Comment by h4x3rotab** [comment]
Yeah, I've checked the screenshot and our source code. Thanks again.

**Comment by raza5402** [comment]
please let me know have you accepted my report?

**Comment by BTGSYSOPS** [comment]
Hello Ali Raza,

Note that we do _not_ accept any reports thru Github that are not directly related to the code hosting on that repository. Please fully read our Responsible Disclosure policy at https://github.com/BTCGPU/dev/blob/master/responsible-disclosure.md which also outlines the right point of contact as well as the scope reports can be submitted for.

Finally instead of opening two reports, you could have simply updated the other report. Duplicate posts will create extra work and will not aid your reports to be handled in a timely fashion.

This discussion will now stop here. If you have any reports, you can send them to the correct locations. This ticket has been closed.

/SYSOPS/
