### ISSUE TITLE
 CVE-2019-6250 - libzmq 4.x is vulnerable.

### ISSUE THREAD

**Issue by EvertonMelo** [BTCGPU/BTCGPU#382]
CVE-2019-6250 - libzmq 4.x is vulnerable.

## Description:

A pointer overflow, with code execution, was discovered in ZeroMQ libzmq (aka 0MQ) 4.2.x and 4.3.x before 4.3.1. A v2_decoder.cpp zmq::v2_decoder_t::size_ready integer overflow allows an authenticated attacker to overwrite an arbitrary amount of bytes beyond the bounds of a buffer, which can be leveraged to run arbitrary code on the target system. The memory layout allows the attacker to inject OS commands into a data structure located immediately after the problematic buffer (i.e., it is not necessary to use a typical buffer-overflow exploitation technique that changes the flow of control).  

## Exploit details

Now that msg_size_ has been set to a very high value, the attacker is allowed to send this amount of bytes, and libzmq will copy it to its internal buffer without any further checks.

This means that it's possible to write beyond the bounds of the allocated space.

However, for the exploit this is not necessary to corrupt memory beyond the buffer proper.

## P.o.C
Remote code execution vulnerability [#3351](https://github.com/zeromq/libzmq/issues/3351)

### fix: 
[libzmq 4.3.1](https://github.com/zeromq/libzmq/releases/tag/v4.3.1)
#381 

###  References: 
[CVE-2019-6250](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-6250)

**Comment by EvertonMelo** [comment]
no need to thank, just continue with my work:

my address btg is:

Gao5Qx8zJhSdaVSndZjNsMnWjjkvxEQ3kL

**Comment by BTGSYSOPS** [comment]
Thank you for report this. However there are several issues with your report which prevents us from accepting your report:

- Although libzmq might be used within this software the PoC does not prove any vulnerability within the BTCGPU software, only in the library referered. For a report to be valid YOU must proof an actual vulnerability within OUR software with a (working) PoC that can be reproduced with our most recent codebase. Referring to some external source assuming the software is vulnerable based on a detected version is not a valid argument here.
- The issue was reported by guidovranken on libzmq github, as he was the person to have found the issue it does not seem eligiable, expecially because of the previous point.
- The feature that uses this library uses it for a very specific method, which is only used and designed to be used in trusted/closed environment. It cannot be publicly exploited unless another vulnerability exists. As such, even if you can proof this vulnerability, the risk would be extremely low

Please send us a working PoC on OUR codebase, after that we can reconsider your report. For now it has been denied.

**Comment by EvertonMelo** [comment]
@BTGSYSOPS  

there are as many inconsistencies as delays on your part. 

Please read carefully: 

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-6250 

what is MITRE and CVEs

https://cve.mitre.org/about/index.html

Anyway, they don't wanna get me ok. 

finally 48 hours from now you canceled this issue.

**Comment by EvertonMelo** [comment]
@BTGSYSOPS  fixed #381

**Comment by BTGSYSOPS** [comment]
As explained in our reply, you must show a working PoC on our code. That the library is present does not mean our software in vulnerable. Only if it would be using the specific methods in that library (which is not likely). That there is a CVE assigned, does not mean it affects all software nor prooves our software is affected. You can only show this by creating a PoC based on our code showing the vulnerability can be used.

As a participant of the Responsible Disclosure policy, you must proof there is a vulnerability. The PoC posted on the Libzmq cannot be implemented within the BTCGPU code, nor do i see any way to implement it.

**Comment by EvertonMelo** [comment]
@BTGSYSOPS  

while you were thinking about 

> the sex of angels

.
Someone did something. #381 ( MERGED ).

Thank you for making it clear that all criteria here are subjective.

**Comment by EvertonMelo** [comment]
> That the library is present does not mean our software in vulnerable. 
OR 
> The PoC posted on the Libzmq cannot be implemented within the BTCGPU code, nor do i see any way to implement it.
and
> Only if it would be using the specific methods in that library (which is not likely). 

only one response: 
![BTCBULSHIT](https://user-images.githubusercontent.com/7637553/61789347-d8a2a100-adea-11e9-93a2-c22381d71d94.png)

**Comment by MentalNomad** [comment]
Yes, Bitcoin Gold includes ZMQ, just like Bitcoin.

And the version of ZMQ we use has a vulnerability. 

But it seems that neither Bitcoin Gold nor Bitcoin use the part of ZMQ that is vulnerable.

"From the perspective of bitcoingoldd, the ZeroMQ socket is write-only; PUB sockets don't even have a read function. Thus, there is no state introduced into bitcoingoldd directly. Furthermore, no information is broadcast that wasn't already received from the public P2P network.

No authentication or authorization is done on connecting clients; it is assumed that the ZeroMQ port is exposed only to trusted entities, using other means such as firewalling."

https://github.com/btcgpu/btcgpu/blob/master/doc/zmq.md#remarks
