### ISSUE TITLE
1300 blocks reorged: network attack?

### ISSUE THREAD

**Issue by c0deright** [BTCGPU/BTCGPU#402]
https://www.reddit.com/r/CryptoCurrency/comments/howyqu/btg_just_had_a_network_attack_that_replaced_1310/

Running 0.17.1 and this happened on my node, too.

The new chain is active, new blocks are being mined on it but

  https://explorer.bitcoingold.org/insight/
  https://btgexplorer.com/

both are on the old, not-reorged chain (how come?).

Any insight on what happened? Network attack?

**Comment by c0deright** [comment]
So you knew someone mined BTG blocks in private to reorg the chain and informed selected pools and exchanges and released v0.17.2 but did not stress the fact everybody should update?

What a f*cking shitshow!

How about next time you use the github release details to make it clear it's an important release and everybody should upgrade?

https://twitter.com/bitcoingold/status/1281713559265849347
https://bitcoingold.org/emergency-update-0-17-2/

**Comment by MentalNomad** [comment]
No, our monitoring indicated a massive attack chain being mined, so we informed **_all_** pools and exchanges that we could reach. However, not all pools and exchanges immediately respond or indicate whether or not they've upgraded their nodes. Not knowing immediately who has upgraded, the team could not have been certain in the first day if:

1. Enough pools had migrated to ensure the honest chain would continue to be mined if the attacker released their chain, or
2. If the targeted exchange(s) (whoever they were) had yet upgraded, so that they would be protected from a double-spend attack.

**Under the circumstances, a public announcement of v0.17.2 would have only served to alert the attacker**, prompting them to immediately release their attacking blocks before some pools and exchanges were ready. This would ensure the greatest chance of successful attack against an exchange, and likely cause immense confusion among the pools and miners. This would be terrible for miners and for the BTG markets. To have made a public announcement at that time would have been stupid and foolhardy.

By waiting several days - during which we gradually got acknowledgements from multiple smaller pools and exchanges - we ensured that the defense was in place before the attacker released their chain. **The network - and the Community - successfully rejected a 1309 block attack, no pools lost honest rewards in a rollback, and no exchange lost funds to a double-spend.**

Notable: the attack was released around 16:30 UTC on July 10. After the attack, we announced v0.17.2 publicly, and the attack was in the news that evening. The attacker continued to mine until the next morning, with their last block being found 9:05 UTC on July 11.

Start height: 640568, 00000001ca8ac90d83f6f5da01ac96b7a017702a040953b93cda2e52b07385cd
Stop height: 641991, 00000003c65e79c53f1623db72ef56d35341f16b47e7aafc21ad5bc430476978

This was a total of 1423 blocks mined by the attacker.

Even after the attack and the news, a few smaller, less-used pools continued to mine on the attacker's chain. The team worked incessantly to try to get their attention. Only one block was mined on the attack chain after the attacker stopped:

Attacker's last block:
2020-07-11T09:05:26Z UpdateTip: new best=00000003c65e79c53f1623db72ef56d35341f16b47e7aafc21ad5bc430476978 height=641991

Stray pool, 2.5 days later:
2020-07-13T17:58:41Z UpdateTip: new best=00000003209d9ed6d373db4d1bf1b5f8b08c64eb3894b7820d69e5dcdb0b5d39 height=641992

This was the last block seen on the attacker's chain; about 12 hours later, the honest chain had accumulated more work than the attacker's chain, and all nodes re-converged to the honest chain. Even if this stray pool still hasn't upgraded their node, they are now on the same chain as the rest of the network. If the pool ops don't respond, there's not much we can do; the BTG network is decentralized.

I'm now closing this issue.
