### ISSUE TITLE
not connecting to network

### ISSUE THREAD

**Issue by diadal** [BTCGPU/BTCGPU#418]
unable to sync not connected to nodes

**Comment by MentalNomad** [comment]
You are experiencing a bug in DNS seed & hard-coded backups.

The code to fix this bug is already committed, but not deployed to an official release. If you are building from source, implement this commit: https://github.com/BTCGPU/BTCGPU/commit/cae5e1b1107a2df0ac3cd73391f372e957c8e3ee

If you are using our pre-built binaries, you can simply add a small number of manual peers (two or three) from this list of long-standing, high-uptime peers: https://status.bitcoingold.org/dl.php?format=config

Just select a few of those at random and add those lines to your bitcoingold.conf file, and restart your node.

One example for bitcoingold.conf:
`addnode=62.141.35.89:8338`

If you want, you can alternatively enter them through your node's console (Help, Debug, Console.)
This same peer as above, formatted for the console:
`addnode 62.141.35.89:8338 add`

Once your node connects to a few peers and begins to bootstrap, it will pick up a large number of additional peer IPs and will begin to connect to them automatically until you have 8 outbound peers.

After your node begins to sync and has a couple of additional peers join from the network, it will actually have a lengthy internal list of potential peers. You may want to restart your node at this point so that it can join to a more random set of outbound peers.

**Comment by diadal** [comment]
working now
