### ISSUE TITLE
Code audit link?

### ISSUE THREAD

**Issue by adnandoric** [BTCGPU/BTCGPU#65]
Hi,

Can you please provide the link to the audit results of your code, if the code is audited?
I couldn't find it anywhere on your website.

If it's not audited, when it will be? The deadline is approaching.

Thank you

**Comment by Lancelight** [comment]
Uhm,  it's not an open source project,  therefore it will never be "audited".  BTG is just a facade money grab by the devs and their pre-mining horseshit.  The block has already past and they STILL dont have any of the promised code in the codebase.  Most important of which is Replay protection.  BTG DOES NOT HAVE IT.  They cant point to it in the code,  therefore it doesnt exist.  Simple.

**Comment by pezcore** [comment]
@Lancelight  What do you mean it's not an open source project?

**Comment by Lancelight** [comment]
@pezcore In order to qualify as an "open source" project,  one must actually PROVIDE the sourcecode.  This did not happen and therefore it does not qualify.  The code that is currently available is NOT the code that is planned to be implemented.

**Comment by h4x3rotab** [comment]
@Lancelight Are you sure? Your comments suggest that you didn't understand the common workflow of GitHub. You should be aware this is a work in progress. Every ongoing changes can be found from our [pull requests](https://github.com/BTCGPU/BTCGPU/pulls). You can also find merged pull requests in our [commit history](https://github.com/BTCGPU/BTCGPU/commits/master). At least you can check the daily updates on our website [here](https://bitcoingold.org/category/development/).

**Comment by Lancelight** [comment]
I didnt just pull that idea out of thin air nor is it not based in fact.  Commit dates do not lie,  nor do blog posts on the large exchanges (Coinbase comes to mind regarding this topic).  What commits are there NOW (as in the last couple weeks) are completely irrelevant to the point.  The point is that there was NO actual code commits worth a shit for the duration of the runup to the snapshot date.  If you're trying to pass off commit changes that do absolutely nothing other than change names of things like "bitcoin" to "btgold" as actual code changes,  then you must really think a lot of us other developers are really stop or completely illiterate.  I do not consider a cosmetic change commit as a "commit".  I consider it a complete waste of my auditing time.

**Comment by vattay** [comment]
@lancelight, please stop embarrassing yourself, I can only take so much cringe per day.

**Comment by Lancelight** [comment]
@vattay Here you go Vattay,  read it for yourself.  Come back again when you think I'm still stupid.  What I'm talking about is 3 paygrades above your maximum ceiling.  Maybe you should read the code and then you'll understand why myself and 95% of the planet are unhappy with what has actually hit the btg github commit log.

https://support.coinbase.com/customer/portal/articles/2892196-bitcoin-gold-faq   Specifically this quote "At this time, Coinbase cannot support Bitcoin Gold because its developers have not made the code available to the public for review. This is a major security risk."

**Comment by h4x3rotab** [comment]
@Lancelight Stop trolling and learn more about the facts. Have a nice day.

**Comment by Lancelight** [comment]
Read the date of the commit you're referencing,  then read the date of my comments.  Nuff said.

**Comment by mjoh090** [comment]
@vatta - @Lancelight is not embarrassing himself. He is sharing his observations and raising concerns. The concerns that he raises can be addressed by the Dev Team (or those in the know) simply by pointing to realities that dispute the validity of his concerns. 

@Lancelight's concerns should be seen by the Dev team as an opportunity to build confidence by addressing those concerns with constructive argument and reason, rather than mischaracterising his concerns as trolling/abuse.
