### ISSUE TITLE
Reclaim unused coins

### ISSUE THREAD

**Issue by mk229797** [BTCGPU/BTCGPU#69]
Inheriting user base from Bitcoin has its advantage, however many private keys ware lost, and lots of coins are not accessible. SegWit has improvements to UTXO, so it should be quite easy to BURN coins that did not move for e.g. 5 years - this way amount of money in circulation will be guaranteed to be 21m, also additional block reward (if some old money was burned) will be an incentive for miners. To avoid funds being burned user has to make sure to move them at least once every 5 years.

**Comment by mstroehle** [comment]
In my opinion this is a very bad idea. In future your digital stuff will may live longer than you. Blockchain technology can be the way how we handle money. Are you happy if someone writes in his last will that you get the private key for his cryptocurrency and it is burnt because of the aboved mentioned function? Giving a forecast about the economy for limited and unlimited coins is not trivial. These systems are very sensitive.

**Comment by mk229797** [comment]
This feature can have with sunset mechanism (e.g. disable in 5 years), beside its time to shake the barley and see if owner of those 50 BTG wallets (worth together 1000000 BTG) is still alive ;)

**Comment by Lancelight** [comment]
What retard thought up the burning idea?  What planet are you from,  Retardanus?  This is exactly why BTG is going absolutely NO WHERE.  It has zero brains behind it.  You dont burn other people's long term investments you idiot.

**Comment by krtschmr** [comment]
so, satoshi is burned? RIP satoshi :(

**Comment by justvanbloom** [comment]
a bad idea.

**Comment by tbbw** [comment]
You cant tell what coins are lost and what coins are just someones cold wallet.
What would stop me from picking some random wallet and say "hey those are my coins and i lost the keys in a harddrive crash a year ago"... can you give those coins to me?

**Comment by mk229797** [comment]
@Lancelight - TL;DR. Messages from accounts without github history are ignored

**Comment by mk229797** [comment]
@tbbw you snooze, you loose. What you don't like my final solution? :) You have to admit that OTXO is bloated with dead wood.

**Comment by Lancelight** [comment]
@mk229797 Stick to rock wheels and caves,  the modern world is to far above your intelligence to explain why this would be the dumbest of all the suggestions seen so far.  The only thing that's bloated is the air you have upstairs.  If you cant comprehend the common sense as to why this is dumb,  you shouldnt be allowed to handle a keyboard.

**Comment by krtschmr** [comment]
@mk229797 your idea is good to claim back money, but your idea also is killing the whole trust that cryptocurrency is giving us. 

yes indeed, i could actually claim back my ~30-40 BTC that i lost 3 years ago when my computer was confiscated (and never gave back). bad luck for me, i should have had a backup (oh wait, that backup exists but i can't access it because i need another backup which is also belly up since *insert random bla*). it's my personal failure and i have to live with it.

your idea is in general a very bad idea because: 

- what happens if i deposit 100 BTC at my lawyer and in case of my death, my children should get them? they'll access the wallet and it's *burned*. thank you daddy, you selfish soab. huh? 

- what happens to satoshis coins? *claim it or fuck it!* ? comeon... 

- what happens to people that are forced to 6 years in prison? can't access their hard earned millions after they get released?

- what happens to those people who forgot about their bitcoins but then found a paperwallet in a locker? because they didn't care they lost?

- if you keep your money on a bank for 20 years it's still there (or bank is belly up). why should this change?

- bitcoin / crypto should improve the financial world. your idea is making it less trustworthy

**Comment by Thecreator1** [comment]
Dear mk229797,
Lancelight is very correct in his statements.
You are an idiot of the most marvelous kind.
I have put away some wallets for my grand children and they will get it when they turn 21, which is well over five years.
This would mean that they will be left with nothing if it ever comes to your idiotic visions.
Why don't you burn your own wallets in stead? 
Please do it now.

**Comment by EliasZ** [comment]
Even in "real banking", plenty of people have bank accounts with funds resting for more than 5 years. Especially on a public blockchain, where each transaction from a veteran address will have eyes on it immediately (and might even cause price reaction depending on which address!), it is very much possible that untouched wallets are just cold funds.

Removes a lot of trust if a mechanism can nullify funds based on some arbitrary mechanism like time. Right now it might be 5 years, in a bit 2 years and a tad later when someone pushes a button. That's not what the distributed ledger was intended for.

**Comment by krtschmr** [comment]
the onliest good thing of *burning* would be the implementation of fungibility.

*burn your coins*, prooven with a mathematical algorhytm and you can create 1.0 new coins that are untraceable. i read recently about a coin that has this feature but i forgot about it. every other burn is dumb.

**Comment by mk229797** [comment]
@krtschmr - _reclaim for economy_ (as premium reward in e.g. next 10 blocks), so valuation of token can be honest - how many usable tokens are there? If there is less usable tokens then minted, market cap should be adjusted - but currently cannot do that because cannot tell is some tokens are legitimately stored in cold wallet, or if the key for them is lost. If half of the tokens is lost, there is less tokens to exchange with, which means less money in circulation, and unnecessary economy stagnation. Have to make right choices. Blockchain protocol replaces central bank (https://imgflip.com/i/1y5e2t), so it should make sure that it's economy is sound. To answer your questions:
- yeah, you should do a time locked transactions on multisig wallet that would their greedy hands to take over of your assets as soon when you are cold, or maybe create a oracle transaction (for sure in future there will be a service that could store on blockchain hash of file with deceased people, that's why SegWit improvement is here - see https://github.com/adiabat/adiabat.github.io/blob/master/dlc.pdf)
- fuck it - it's 1 million of them, he has BTC anyway :)
- see above
- of course it should be made public to made people aware about this feature
- no its not - unclaimed assets go to state
- if rules are know, how it is making it untrustworthy?

**Comment by mk229797** [comment]
@EliasZ every rule in consensus is arbitrary, its called code for a reason - bunch of if statements.

**Comment by krtschmr** [comment]
@mk229797 

*no its not - unclaimed assets go to state*
this is not true. if i deposit my money for 20 years it's not unclaimed. it's only unclaimed if i die and nobody claims it.

*if rules are know, how it is making it untrustworthy?*
if the rules are changed, the changes makes it untrustworthy. imagine if the bank announces "well, you better move your money till tomorrow or it's gone" - but you're sleepin on cuba with a bottle of wine in your arm and missed the 5 year timeline. money gone seems to be a bad idea for you.

**Comment by Thecreator1** [comment]
Do something constructive in stead of destructive and try to recover those lost coins in stead of destroying them, which is not going to happen by the way.
Please destroy your keyboard.
Do it now.

**Comment by Lancelight** [comment]
@mk229797 Lol you actually believe this is an idea with debating?  Really?  This would be like saying "Let's suck all the oxygen out of Antarctica just because no one lives there so that we can use it here instead".  It makes absolutely zero sense.  You're even more dense than I thought.  I figured you'd come back and say "hmm yep,  that was stupid,  ok next idea!".  

Get off the idea of burning.  Moving 150million in BTC just so it doesnt get 'flagged' is not only stupid,  its suicidal and counter productive to the entire point of a blockchain to begin with.  You can keep your virus laden shitcoin,  I'd want nothing to do with a self exploding coin.  If I want things to explode,  I'll blow them up myself.  I dont need some retard developer doing it for me just because he has fewer braincells than the bologna sandwich I had earlier.

**Comment by azeyrx** [comment]
You don't throw your money out the window because you don't need it, but save it for a car or a house ;) ?

**Comment by mk229797** [comment]
@azeyrx I think lots of people have problems with understanding that cleaning up UTXO will not affect them in anyway. If you do not use money, you should be punished (in real world the idea about negative rates was present for a while, not it did become reality).

**Comment by mk229797** [comment]
@Lancelight , @Thecreator1 get out of github, your only achievement in life is owning a GPU (a graphic card if you do not know what this acronym stands for) - understanding what pointer is in C would blow your mind, go back to Facebook.

**Comment by Thecreator1** [comment]
I aint going nowhere.
The only thing that needs to go is your idiotic ideas.

**Comment by aiopa** [comment]
Please dont. I have BTC that are older than 5 years, and i have no plans of moving them. The whole point of a blockchain is that this should not be possible.

**Comment by mk229797** [comment]
@aiopa - consider it RICH tax :) but its only transaction fee cost - so like nothing.

**Comment by Lancelight** [comment]
@mk229797 You repeated attempts to insinuate that Im not actually a developer are hillarious at best and just plain stupid at worse.  I know more about pointers, headers, loops, overrflows and whatever other 'tech jargin' you want to attempt to bring up than you could possibly imagine.  Ive been coding longer than you've been able to reach a keyboard.  I have no need for a public portfolio anymore to sell myself to prospective job interviews like you need.  Thats the difference between you and I.  I am already established in my career and you are not.  So I wouldnt be so quick to judge based on lack of some retarded public git repo portfolio because I have no need for it which is obviously beyond your toddlers brain wisdom.

I do however monitor technology that I use and will call out stupid ideas when they are presented,  such as this.  Infinance,  you dont 'burn' anything just because the holder hasnt used it.  If this was to be a NON-forked project,  then you could consider it.  But its not.  So such an idea is utterly rediculous.  The original BTC holders did not signup to have their dividends burned by some bloatware happy uninformed dev.  You cant steal someone elses data (forking == copying and imo == stealing if things are deleted) by forking it and then delete it just cuz pal.  It doesnt work that way.  If you want such a retarded coin,  start with a BLANK blockchain.  Dont try to mooch off bitcoins success.

**Comment by Thecreator1** [comment]
Let's leave this peanut brain Lance... He ain't worth out time..

**Comment by mk229797** [comment]
If you did not notice this is not a https://github.com/bitcoin/bitcoin or https://github.com/btc1/bitcoin - go wank off over there

**Comment by Lancelight** [comment]
If you did not notice,  this uses BTC's hard earned USER BASE (AKA the blockchain that was just snapshot which in turn makes it a 'fork' of BTC and carries MY DATA in it).  If you dont like it,  go make a REAL altcoin and start from scratch like LTC, Ethereum, Vertcoin (Each of these 3 coins addresses real world issues and solves them in their own unique way WITHOUT copying the BTC blockchain and were successful based on their technical merits alone,  not because they have everyones data), etc.  BTG has absolutely NOTHING to offer over Vertcoin other than the fact that it stole the userbase of BTC in order to market itself.  BTG is nothing more than a cash grab by greedy devs.  Of which I do not approve.  BTG made NO technical improvements that are not already available in other altcoins.  Vertcoin is where people need to look for a GPU minable coin,  not BTG.  It doesnt release sourceode (I would know, I've been looking for it so I could audit it myself),  it doesnt have a website worth a damn with any useful info in it, and has PLENTY of empty promises, and lots of stupid ideas floating around (that never actually get implemented.... well, because they are stupid ideas).

**Comment by Lancelight** [comment]
I'll leave you with this.  Nuff said,  this subject is closed,  it's a retarded idea and should never be implemented on a forked BTC chain.  Ever.  https://www.youtube.com/watch?v=dLLUIeHH-3A

**Comment by mk229797** [comment]
Well I could not agree more, its like Bitcoin Z but with userbase stolen from BTC and that greedy premining - so what? You do not have to use it, and I can bounce off ideas on any github repository I want. Your BTC, BCH and B2X are unaffected. You do not have to use BTG. You got some data on public ladger - so what. You got pictures on Facebook - and you do not own them neither. Beside all this discussion and offending has no point - if BTCGPU devs will decide to implement  this or other ticker that I had risen its their choice.

**Comment by Lancelight** [comment]
The problem is that the devs in BTG are stupid enough to look at this dumb idea and think it's actually worthy.  So it's up to smarter people like myself to point out that it's NOT a bright idea.  Look, your idea isnt bad in certain scenario's.  But when it involves other people's data that did not signup for deletion,  then it becomes a monumentally stupid idea.  If this comment were in the repo of some coin that hadnt even been released yet,  then sure,  a debate could be brought up about it because it would be shot down so fast that it wouldnt actually make it.  It would kill the public's interest in the coin because it would make it an unreliable store of information which is exactly what the blockchain goal is supposed to achieve,  a reliable trustworthy store of information that is always true and correct.  That's why I stated that this idea is completely counter intuitive to what blockchain does in the first place.  If you could convince an altcoin with no userbase to use your idea,  kudos to you.  I'd love to see it,  might even use it if I need a coin that would simply disappear after a certain amount of idle time (like, I cant think of a single use case I'd want that).

Here's a question.  What use case for the user would this solve in an EMPTY blockchain.  Or better yet what use case does this have in a full blockchain like BTC other than it's an inconvenience to have to copy a large blockchain from one device to another.

**Comment by mk229797** [comment]
Well, I have different point of view and do not see anything wrong with this experiment in vivo (if approved), negative interest rates (Silvio Gesell) as tax (miner fee) on holding money could quite well for finite money supply system, plus it would be a way to purge that mess with lost keys, or tokens send to void in past (Mt. Gox etc.) - that's it... I will not participate more in this thread because it is not technical anymore.

**Comment by Thecreator1** [comment]
Every transaction gets hashed into the blockchain this is the true power and beauty because it makes it reliable and tamper proof. 
If you even change, erase, flip, or reverse one bit the whole thing falls apart and stops working.
Besides, you can not distinguish between lost wallets and investors coins which makes the whole idea neglect able.

**Comment by DarthJahus** [comment]
> so it should be quite easy to BURN coins that did not move for e.g. 5 years

Oh, @mk229797 doesn't want Satoshi Nakamoto to get BTG out of his 2009 BTC 🤣

The idea behind the blockchain isn't to make sure all the coins are available, just that all the transactions are genuine.

**Comment by bloggervista** [comment]
No who are you to decide my money if I keep it for 5 years or 50 years. Due one problem we cannot change entire eco system right? We own btc because we can do anything with it. Please trust BTC than government currency because they are the one who controls it. Don't make satoshi sad.

**Comment by h4x3rotab** [comment]
It's not a good idea to touch any coin that not belongs to you. Bitcoin is defined by a set of consensus rules and every transaction & block inside the blockchain. So blockchains must be immutable.

**Comment by therealcmilohernandez** [comment]
the dead coins add value to the system. Please don't burn coins. Not only
is it impossible to distinguished between lost coins and escrow, but you
will be taking away one of the most beutifull concepts of bitcoin and the
blockchain, whci is that no one can mess with your bitcoin even if im dead.

**Comment by therealcmilohernandez** [comment]
Blockchain to be for the people by the people must be IMMUTABLE.  if not
then its just ethereum and ripple working for the new world order.

On Tue, Oct 24, 2017 at 11:42 PM, Camilo Hernandez <cmilohernandez@gmail.com

**Comment by TheComputerGenie** [comment]
> Bitcoin is defined by a set of consensus rules and every transaction & block inside the blockchain. 

Remind me what consensus rules allow for a premine?

**Comment by krtschmr** [comment]
i have to correct myself, saying banks don't take idling funds...


https://www.bangkokpost.com/news/general/1348764/govt-to-seize-money-from-long-idle-bank-accounts

**Comment by dofos** [comment]
@TheComputerGenie Satoshi premined his/their 1 mln and everybody seems to be fine with it. Some are looking for the keys as well

**Comment by DarthJahus** [comment]
@dofos, are you serious? How dare you? Maybe you should take a look at [this forum post](http://p2pfoundation.ning.com/forum/topics/bitcoin-open-source).

**Comment by pezcore** [comment]
no. This is the worst idea ever. Also why even do this?

Is there even a single reason to "burn" (bury?) coins that haven't been spent recently enough?

**Comment by TheComputerGenie** [comment]
@dofos Satoshi and friends being the only miners is **not** the same as a premine. We were all able to mine at the same time as them, just most didn't know it existed; whereas, a premine disallows the general public from mining. These are **not** the same things.

**Comment by Tinkymon** [comment]
@mk229797 i read maybe the first half of all of this.  And your comments and mentality is fucking stupid. Burn the coins? You are what is wrong with this world
