### ISSUE TITLE
did the fork happen? statement?

### ISSUE THREAD

**Issue by krtschmr** [BTCGPU/BTCGPU#70]
did you keep the snapshot? 
statement pls.

**Comment by krtschmr** [comment]
do you stick with the announced block?

**Comment by StarbuckBG** [comment]
Yes!

**Comment by azeyrx** [comment]
After the 491407 block was mined, the fork was completed. That means you could use the BTC right after block 491407 to get the BTG.

**Comment by lacksfish** [comment]
This is messy.. So everyone transacting now on the BTG network chain will not have replay protection?

**Comment by mk229797** [comment]
@lacksfish how you can transact in BTG if the blockchain is not available? I think you mean internal SQL transactions on exchange

**Comment by lacksfish** [comment]
I mean the fork happened at the fork block and now Equihash blocks are generated.. right? Blocks contain transactions, so what would happen if the blocks which are currently being mined are public?

Devs want premined coins, therefore they have to produce blocks in private before public launch.

**Comment by mk229797** [comment]
@lacksfish I guess there ware 100000 blocks generated in few minutes that have only 1 transaction - give 12.5 BTG to miner address, that transaction takes input from nowhere - so cannot be replayed in the real Bitcoin network.

**Comment by lacksfish** [comment]
I can't see the blocks so I wouldn't know. Coinbase transactions for BTG blocks can't be replayed, I agree on that specific point.

**Comment by mk229797** [comment]
@lacksfish is coinbase supporting BTG? Thats strange.... maybe bacuse @jgarzik betrayed again, abandoned segwit2x and now claims credit for atomic swaps (or metronome as he calls it). Anyway no exchange transaction will be reflected on blockchain, only withdraws from exchange to private wallet are recored.

Also there is idea about erasing preminted blocks - another fork... forks everywhere... will you split my magic beans into two? :)

**Comment by lacksfish** [comment]
Coinbase transactions, not Coinbase the company     
https://bitcoin.org/en/glossary/coinbase-transaction

**Comment by adhood** [comment]
lacksfish, the few exchanges that are trading Bitcoin Gold are doing so internally. There is no way to mine, send, receive or interact in any way with the Bitcoin Gold chain at the moment because the mainnet hasn't even been coded yet.

Bitcoin Gold is still in very early stages of development and when they are nearing the actual launch, there will surely be documentation with everything you need to know about using it.

The Bitcoin Gold team called yesterday's snapshot event a "fork". Many people expected it to go the same way as the Bitcoin Cash fork, where the snapshot and launch occurred simultaneously, but this is not the case with Bitcoin Gold. The only thing that has happened so far is the Bitcoin Gold team created a snapshot of the Bitcoin blockchain for future use with Bitcoin Gold.

If you left any Bitcoin on an exchange that is supporting Bitcoin Gold, you should have been credited an equal amount of Bitcoin Gold so that you can begin trading it. However, you will not be able to withdraw or deposit additional Bitcoin Gold until it has actually been created. It's only for trading on that particular exchange.

**Comment by bit79** [comment]
I am wondering what will happen if an exchange allows its users to trade BTC and BTG, and then BTG never happens...

**Comment by shamoons** [comment]
What do you mean the mainnet hasn't been coded yet?

**Comment by bilbobits** [comment]
Best question here, the mainnet doesnt' exist because nobody bothered to make one.

Funny thing on the way to the BITCOIN clone, nobody even read the 'talking papers' about making bit-coin clones. For instance one item is 'magic cookies' that ID bitcoin, nada didn't happen. It's as if a person who didn't know C/C++ did the grep/sed and changed the names on the bitcoin base code, and then didn't bother to do much else.

Obviously all this was just put together a few weeks ago, the team is clearly a team of 'web site developers' and marketing people. They think they can just give away 'shit coins' and "REAL PROGRAMMERS" will step in and work for 'free'?

Nothing has been done, nada, not even a wallet on the Unix cmd-line world,when you build the code you must disable wallet, which means you can't even run 'bgold-cli' to 'generate a new address', ok all is fine, but either another six months of work needs to be done, or folks here need to wait six months.

Questions for "Sammy" ( obviously a smart DEV ), why don't you just make a shit-coin BTC copy with equihash? Hell you know this stuff very well, IMHO you need to just make the code changes and make it happen, with your skill in the world of zcash-proxy you could actually release the miner code first, and then server; Hell with the windows wallet :) But somebody here who grep'd/sed'd this code didn't even bother to compile the code 'ever' prior to the 'FORK', of course it was a fork, I think we should make a new name here called 'SPAF' for spam/scam.

If not for the CHINA guy and a few people, this low level project would have never seen light, it has NO possibility of going live in the next 30 days, unless they pay the normal $50 fee for a BITCOIN-CLONE and have a BOT do it right.

The exchanges are selling this SPAF-COIN for +$500USD, so like bitcoin-z, this puppy will go back to 1-2 satoshi, before the first coin is ever mined, and there it will stay.

Lot's of people are going to OWE real money to these exchanges for this SPAF 

BITCOIN/EQUIHASH is a good idea, in since its already here in zcash, bitcoinz, zen, zclassic; It's still a good idea, but DO the CODING FIRST, release it, test it, and then let it go, and don't premine, but make it a fair start.

IMHO this SPAF-COIN will never be mined, you can't even copy over the existing blocks/chainstate because there is a 'size conflict', all those Dumb sheep who were promised spaf-gold, and then they closed trading of BTC for 24 hours around this, goes to show the that BITCOIN community is controlled by the exchanges, morons, and idiots.

All of SATOSHI's original dreams are dead, sure BTC is worth $6000 today but that's it, you can't buy a coffee, cuz the fee's would cost more than the coffee.

Could this coin have been created just to once and for KILL BTC?

The fact that morons can create a 'fork' and disrupt all exchanges shows that consensus is over seen by the lowest common denominator fool in china.

**Comment by StarbuckBG** [comment]
I will close this issue. More information can be found on BTG FAQ: https://btcgpu.org/faq/ and the roadmap: https://btcgpu.org/wp-content/uploads/2017/10/BitcoinGold-Roadmap.pdf
For discussion you shall use Slack: https://join.slack.com/t/bitcoin-gold/shared_invite/enQtMjYxMDU5NzQzNjUyLTJlODRhYjg2NGRmMzE4ZjBkZjlmOGM0ZDc0OGUyMDZmMTVlY2RjZDc2OWQ0NWY2NWI0ODcyZjYwZTVhMjQ5OTE
