### ISSUE TITLE
Start at block #1 instead of having to DL entire blockchain to date

### ISSUE THREAD

**Issue by adaseb** [BTCGPU/BTCGPU#71]
I think what needs to be done is instead of forking-off the original Bitcoin blockchain is to simply just include all the coins in existence with a premine and just start with the Genesis block. All addresses would be credited exact BTG as the snapshot time.

There are way too many of these Bitcoin forks and its annoying to download and sync. Especially with the coin so new and lack of nodes. Downloading 150GB is really unneccessary.

**Comment by Lancelight** [comment]
It doesnt work that way.  The "coins" do not actually exist.  They are nothing more than 1 long transaction that goes all the way back to the original mining machine.  In otherwords,  1 coin (and all of it's satoshi parts) are distributed everywhere all over the place via transactions.  You cant just slap them together in 1 bucket and call it a "coin" that can be ported to another chain.  You literally have to mirror (AKA fork) it in order to preserve account balances/addresses, etc.  You should stick to using pen and paper.  The technology sector is to complicated for you to understand.

**Comment by krtschmr** [comment]
good idea, technically not possible

**Comment by mk229797** [comment]
@adaseb There is a project called Bitcoin Z that did actually the same thing - look it up.

**Comment by azeyrx** [comment]
If we start with block 1, you wouldn't call this a fork anymore, but simply a new coin.
In addition, all owners who currently own BTC would not get the same number of BTG (1:1)

**Comment by mk229797** [comment]
is it a fork when 100000 new coins are minter in few minutes?

**Comment by Lancelight** [comment]
@mk229797 a fork is a fork is a fork no matter what happens AFTER the fork.

**Comment by DarthJahus** [comment]
> If we start with block 1, you wouldn't call this a fork anymore

@azeyrx, do you really think BTG is a "fork"? It doesn't really fork from Bitcoin because of a disagreement, it takes a snapshot and starts from there. It's an altcoin.

**Comment by Lancelight** [comment]
It uses the same blockchain data and therefore it qualifies as a fork.  Its
no different than forking a repo.  No matter what happens to it AFTER the
original codebase,  its STILL a fork.

**Comment by bilbobits** [comment]
FUBAR,
There are dozens of papers posted since 2011 on how to clone BITCOIN, its clear that NOBODY on this B-GOLD team bothered to learn how to clone bitcoin. Not even 1/2 the work has been done yet, and the funny thing is you can buy this service on line for 0.1 BTC

1.) They promised all prior BTC holds a BTG so they must use the fork-block (N) as the origin, and not zero or one. Obviously this was the CARROT that made all the exchanges play ball with the scam-fork (SPAF)

2.) Normally when I clone a BTC, and fork, I copy over the exists blocks ( 200GB ) as it takes 2-3 days to reindex or do it from scratch, but not this puppy, I made a copy of current BTC block/chain, and the code will not even process it, because the geniuses are coded block size as 2MB, and thus this thing is not backward compatible with legacy BTC, ok easy fix, but this is the DEPTH of 'klusterfuck' in this SPAF-LAUNCH.

**Comment by marki555** [comment]
@bilbobits won't it be theoretically possible to read the BTC blockchain from beginning to end and just remember the present balances on all addresses? And then create a new blockchain from block 1 which would "mine"/assign those balances to all those addresses? Of course it won't all fit into only 1 block, but it also won't be 150 GB.

**Comment by krtschmr** [comment]
pruning, ya?

**Comment by marki555** [comment]
yes, something like pruning the old history, but keeping balances. My question is not related to BTG, just thinking if it is technically possible.

**Comment by Lancelight** [comment]
Wow you people are thick.  There are no COINS you geniuses.  A coin is a transaction.  1 LONG transaction from beginning to end.  So,  if you copy a "balance" from one chain to the other,  you have to copy the entire transaction history along with it because that IS the coin.  You can just make a "coin" without a transaction.  And you cant make a transaction because you dont have the private keys.

Sometimes I wonder how people can be so stupid.

**Comment by marki555** [comment]
@Lancelight I don't agree that it is 1 long transaction. Each move of coins is a transaction. My theoretical question was referring to making the balances available the same way a block reward is generated - transaction has no inputs, but only outputs. I wouldn't need all the private keys for it.

Also I didn't want to prune a BTC blockchain, it was just an idea for a new coin which could retain balances, but wouldn't need to retain the entire 150 GB history. (The usefullness of another coin is a different question.)

**Comment by oriolpont** [comment]
Balances are a wallet abstraction, so you cannot really copy them.
However, you can do something equivalent: 
- Set the forking block as BTG's genesis block
- Define, as a consensus rule, an initial state of the UTXO database that corresponds to BTC's one at forking time
- Add any premine there, scammy as this might be

**Comment by Lancelight** [comment]
Even if it's possible,  the question of "Why?" still remains.  The only answer I can see is "To mooch off btc's userbase rather than own technical merits".  What is the point of using "balances" as a carrot to get people to use it?  That's not a carrot,  thats a pile of garbage.  Why not use a new cool feature as a carrot instead.  That way the coin value isnt diluted because everyone has a ton already.  The harder coins are to get,  the higher their valuation.  Simple 101 economics.

**Comment by joesixpack** [comment]
Vertcoin is a Litecoin fork -- not comparable.  The point here is to have the Bitcoin blockchain supported by GPU mining.  Nothing more, nothing less.  New gee whiz coins are a dime a dozen and have a snowball's chance in hell of ever succeeding via mainstream adoption.  For better worse worse, Bitcoin is it along with the few other major "King of the Hill" algorithms.  And while I think Bitcoin Cash is all hot air so far, the price is nothing to sneeze at.

There are self-pruning methods available but as long as any are not part of Bitcoin Core, they're not part of BTCGPU.  Simple as that.

But, yeah, it would be nice if we didn't have to waste 150GB of disk space as a "Full Node".  But if we all start advocating modification of BTCGPU to be "smarter, better, faster" than Bitcore Core, then it becomes just another coin instead of a mining extension of the premier one.

**Comment by oriolpont** [comment]
@joesixpack BTCGPU/Bitcoin Gold is quite clearly another altcoin already. Its only advantage (?) over others is that it shares Bitcoin's wide distribution (the widest in a cryptocurrency, by a huge margin).

This issue #71 is just a technical detail, comparable to _headers-first_ or _checkpoints_. It does not change anything fundamental about the coin.

**Comment by commiecoin2** [comment]
i have made communism on bitcoin thank me later
