### ISSUE TITLE
BTG price down

### ISSUE THREAD

**Issue by francois007** [BTCGPU/BTCGPU#84]
The biggest mistake was to launch this coin without a working wallet!

Regards,
François

**Comment by bilbobits** [comment]
Wallet? Your a funny guy. The biggest mistake was launching code that doesn't compile ( never tested ), that doesn't work ( still can't download blocks ), there is no DNS ( nobody even bothered to config a DNS on the website DNS server ).

Not a wallet on linux cmd-line, and never will there be a windows wallet as that takes 'real programming'

Hey, it can still be fixed, maybe ppl can run over to bitcoin-z?

Wallet isn't even 1% of the problem here, the code don't work, it was never tested, the BTC-CLONE was done by a person who didn't even bother to read the notes on 'how to clone bitcoin'.

Now its 24+ hours after the fork block has passed, and not one iota of the software is working, nor does a testnet exist, nor dns seed.

Please ppl, take the time to read the 50+ posts and the answer here on GITHUB and see the depth of incompetence. 

I suspect that the chinese manager is a hard ware cuy, its says that BTCGPU is an ASIC-DEPLOY team, thus it would make sense they haven't a clue about coding.

The really thought they could just launch, and exchanges would go along and then they could pass free BTG's back to developers to actually WRITE the code, that WILL NEVER EXIST.

**Comment by StarbuckBG** [comment]
Do not attack based on assumptions. 
The code compiles, there is DNSSeed make : https://github.com/StarbuckBG/bitcoin-gold-seeder <https://github.com/StarbuckBG/bitcoin-gold-seeder>
Here is absolutely working and compiling client: https://github.com/StarbuckBG/BTCGPU. If you cannot follow the instructions you can ask, how to compile it.

**Comment by francois007** [comment]
Hello Mr. StarbuckBG,
I compile source from 20 years...
This source is bugged, it does not compile for any system!
OS how I tested this code:
Debian Jessie and Stretch ---> not work
Ubuntu 14.04 and 16.04 LTS ---> not work
Gentoo ---> not work
Fedora 26 ---> not work

The same goes for Microsoft systems.
This is not an attack, it's the reality!

Regards.

**Comment by StarbuckBG** [comment]
Why it works for me?
I have 2 nodes on testnet on ubuntu 16.04. What is the error you receive ?

**Comment by francois007** [comment]
francois007 BTCGPU # make
Making all in src
make[1]: Entering directory '/usr/src/BitcoinGold/BTCGPU/src'
make[2]: Entering directory '/usr/src/BitcoinGold/BTCGPU/src'
  CXX      crypto/libbitcoinconsensus_la-aes.lo
In file included from crypto/aes.cpp:6:0:
./crypto/common.h:16:20: fatal error: sodium.h: No such file or directory
 #include "sodium.h"
                    ^
compilation terminated.
Makefile:7697: recipe for target 'crypto/libbitcoinconsensus_la-aes.lo' failed
make[2]: *** [crypto/libbitcoinconsensus_la-aes.lo] Error 1
make[2]: Leaving directory '/usr/src/BitcoinGold/BTCGPU/src'
Makefile:9333: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/src/BitcoinGold/BTCGPU/src'
Makefile:729: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by jagottsicher** [comment]
compiling worked  for me on ubuntu 14.04, but no working testnet so far.

anyway you have a point that the main developer team is closed and only taking care their pre-mining works. it is a "typical" Chinese biz habit to keep everything a secret - exactly the opposite what you need when creating a coin on github.

**Comment by StarbuckBG** [comment]
Would you read this doc : ROADMAP <https://goo.gl/g1NeUt>

**Comment by c0deright** [comment]
@StarbuckBG Just include a f*cking libsodium check in configure.ac

**Comment by francois007** [comment]
I think this development is bad...
BTG is Open source? I do not think so!
I think the final price of BTG will be just one satoshi.

Regards.

**Comment by bit79** [comment]
Link to roadmap does not work...

**Comment by StarbuckBG** [comment]
https://btcgpu.org/wp-content/uploads/2017/10/BitcoinGold-Roadmap.pdf <https://btcgpu.org/wp-content/uploads/2017/10/BitcoinGold-Roadmap.pdf>
try this one

**Comment by bit79** [comment]
Works - thank you. Good luck with your project!

**Comment by StarbuckBG** [comment]
Thanks for the support!

**Comment by StarbuckBG** [comment]
Issue with such name is not for github. You can contact is Slack to the team and also you can check the site.
