### ISSUE TITLE
client can't connect to any node

### ISSUE THREAD

**Issue by ilia2s** [BTCGPU/BTCGPU#89]
Debug.log have only this

> 2017-10-25 14:08:00 connect() to [2002:c0bb:74f5::c0bb:74f5]:8338 failed: Network is unreachable (101)
> 2017-10-25 14:08:01 connect() to 37.120.174.32:8338 failed after select(): Connection refused (111)
> 2017-10-25 14:08:01 connect() to [2a02:810a:8840:bb4:7271:bcff:febc:5fc3]:8338 failed: Network is unreachable (101)
> 2017-10-25 14:08:02 connect() to [2001:0:9d38:6ab8:1431:b8cb:e052:9872]:8338 failed: Network is unreachable (101)
> 2017-10-25 14:08:02 connect() to [2001:0:5ef5:79fb:1001:137d:bb6f:b355]:8338 failed: Network is unreachable (101)
> 2017-10-25 14:08:25 connect() to [2001:0:9d38:953c:83f:2620:bdc5:499b]:8338 failed: Network is unreachable (101)
> 2017-10-25 14:08:26 connect() to 37.59.62.226:8338 failed after select(): Connection refused (111)
> 2017-10-25 14:08:26 connect() to [2001:0:9d38:78cf:1060:3d66:b174:e19a]:8338 failed: Network is unreachable (101)
> 2017-10-25 14:08:32 connect() to 209.95.54.58:8338 failed after select(): Connection refused (111)
> 2017-10-25 14:08:33 connect() to [2a01:4f8:192:5230::2]:8338 failed: Network is unreachable (101)
> 2017-10-25 14:08:34 connect() to 103.243.244.14:8338 failed after select(): Connection refused (111)
> 2017-10-25 14:08:34 connect() to [2001:0:9d38:6abd:30c1:1c0c:48a7:4663]:8338 failed: Network is unreachable (101)
> 2017-10-25 14:08:35 connect() to [2a01:4f8:192:5230::2]:8338 failed: Network is unreachable (101)
> 2017-10-25 14:08:41 connect() to [2001:8d8:923:8400::87:ebd]:8338 failed: Network is unreachable (101)
> 2017-10-25 14:08:47 connect() to [2001:0:9d38:6ab8:2043:914:d1c0:4bd9]:8338 failed: Network is unreachable (101)
> 2017-10-25 14:08:48 connect() to [2001:0:4137:9e76:244e:2b42:adff:826c]:8338 failed: Network is unreachable (101)

and getinfo shown zero blocks

**Comment by brbatv** [comment]
I guess it's because the network is not launched yet ;p

**Comment by ilia2s** [comment]
wow, so strange... I suppose that it must be running since yesterday

**Comment by hashmonkey** [comment]
there is NO network :) LOL

**Comment by StarbuckBG** [comment]
The WIP is in #49

**Comment by stefhenry** [comment]
if the network is not ready how come BTG is already traded in so many markets?

**Comment by adhood** [comment]
The exchanges are trading "future" Bitcoin Gold at the moment. If you held a Bitcoin balance on one of those exchanges at the time of the fork they basically gave you an advance of Bitcoin Gold to start trading with. Everything is being handled internally at the exchange since there is no Bitcoin Gold network at the moment. If you trade all of your "future" Bitcoin Gold away, the exchange will simply take the real Bitcoin Gold from your wallet once the real network launches.

**Comment by bilbobits** [comment]
Let's see as of right now,

You can't copy 'blocks' from ~/.bitcoin to /.bitcoingold because they hard coded the block size for the larger blocks, so you must do a virgin run, problem is about every 50 blocks, you must do a -reindex to go back and recover,

There are only a few seed nodes and even they aren't ready

Dev's say people should 'test' but there is nothing to test, you can't run the 'bgoldd' server on legacy BTC because it will not accept it, you can't run on the seednode  because it doesn't exist, there are a few dozen people running the server, but everytime on of them hits the top of the 'new btg blockchain' the system collapses and you must go back and -reindex and hope that somebody else or you has made new blocks

Seems like the people at BTCGPU don't really want there to EVER be a MAINEST or TESTNET, appears that they'll BUY just enough time to cash-out of there ICO on the exchanges and dissapear, note the CHINESE just brought in this EURO programmer Proffessor 'starbuck' two weeks ago prior to this BTG had been a poorly orchestrated ICO since August, about when they got 'banned' in China, which is probably why this puppy got re-packaged as a minable gpu coin.

The trend on the NEW ICO's seems to be NON-MINABLE coin, meaning these people have no intention of this coin to be EVER MINED, inspite of the fact that they say its an NON-ASIC BITCOIN.

The owner of BTG is an ASIC HW guy, killing his own goose is what CHINESE call pissing in your own soup.

Just another ICO fuck, but this time these people have wasted the time of 100's of real DEV's that would like to see a GPU-BTC, I guess you could call BITCOIN-Z this, but its also "FRAUD",

Problem is its now just too easy to pull a non-existent ICO out of your ass and sell it to the public. Nobody bothers with software. Nobody reallly intends anything to be 'mined' as that PARADIGM is over with "Proof of Stake" ( owners who pre-mine make the rules ).

**Comment by ilia2s** [comment]
Is there no any news, yet?

**Comment by litwi1rm** [comment]
dnsseed is working now

**Comment by h4x3rotab** [comment]
DNSSeed is working now. You can compile it and join the testnet. I'm going to close this issue as it's solved.

**Comment by stefhenry** [comment]
When will the production DNSSeed will be available?

**Comment by ilia2s** [comment]
I planned to use a production net. And wait for it since oct/25

**Comment by h4x3rotab** [comment]
You are not well informed. Please check our roadmap. Oct 25 is the fork "snapshot" date. We launched our testnet recently but need a few more days to launch mainnet because we must make sure the security.

**Comment by stefhenry** [comment]
A few mining pools said they would start mining on November 1st, this date is already past, and you're talking about a testnet only. It looks like this project have no clear roadmap, or it is not advertised enough.

**Comment by TheComputerGenie** [comment]
@stefhenry Many said Nov 1 based on what @h4x3rotab said (and was retweeted)
https://twitter.com/bitcoingold/status/920724127996104704

**Comment by ilia2s** [comment]
"few days" in the official road-map it's bad project management and PR
