### ISSUE TITLE
Is BTCGPU an equihash algo coin?

### ISSUE THREAD

**Issue by MCrypto** [BTCGPU/BTCGPU#97]
i thought this was an equihash based coin? or is it a fork from bitcoin? 

and before just closing the thread, it would be nice to explain a bit? ( #95 )

**Comment by DarthJahus** [comment]
Bitcoin Gold is a Bitcoin fork, it takes Bitcoin code but changes the Proof of Work algorithm from SHA-256 to EquiHash. This only concerns the way mining (and consensus) is made. The address format has nothing to do with that.

And since you are asking about Z addresses: It's something (zSnark) added by the other coins. It's like another functionality. Maybe Bitcoin Gold can consider adding it… With all the premine money, I'm sure they can afford adding new features (and quit their dayjobs) for years :)

**Comment by MCrypto** [comment]
I was just looking at VertCoin (which is Lyra2RE v2) and compiling it, it looks exactly the same as the code here?

**Comment by DarthJahus** [comment]
They all look alike because they are based on the same concept (P2P, Transactions, Proof of Work, etc.).

Each coin comes with something new and adds it to its own code, or changes a part of the base.

Take a look at XVG, for example, they are adding a new protocol that obfuscates the blockchain and may make it impossible to look at with classical blockchain explorers.

**Comment by MCrypto** [comment]
thank you @DarthJahus  :)
