### ISSUE TITLE
Will main features complete by the time?

### ISSUE THREAD

**Issue by John1231983** [BTCGPU/BTCGPU#98]
The BTG has about 5 days until the deadline. However, we have some issues that need to solve.  DO you believe that you will complete these works in the time? I ask it to decide to buy BTG or not. Now the price is 103usd/ 1btg. I hope it will go up if your team can complete the main features that shown in website. Please do not scame us

**Comment by francois007** [comment]
I think that the final price of BTG will be just one satoshi.

Regards.

**Comment by John1231983** [comment]
I have bought 2 BTG at 93usd. I hope it will rise. I believe them@@

**Comment by Thecreator1** [comment]
It has been known for several day's now that this project has failed.
You can not even buy 2 BTG because there is no active Mainnet.
You have been scammed, probably by a fraudulent exchange that offers fake BTG.
Consider your funds lost.

**Comment by John1231983** [comment]
Really. I bought it in bifnex. We must wait until nov. 1

**Comment by Thecreator1** [comment]
It's not possible because there is no Blockchain yet.
It's clear that you do not have a clear understanding about Blockchain Technology.
Every transaction get's logged onto the Blockchain and this is not possible without one.
So i don't know what you have bought, but i know it's definitely not BTG. 
You have been scammed.
Consider your funds lost.

**Comment by h4x3rotab** [comment]
It's future trading

**Comment by Thecreator1** [comment]
It's a scam.
That price feed can be manipulated by whoever controls it simply because it lacks a Blockchain.
They are selling FAKE BTG it is impossible to ad the transactions to the Blockchain on a later date and you know it.
Consider your funds lost.

**Comment by D3m0nKingx** [comment]
I wish I could slap these idiots, seriously the misuse of what github was created for is just preposterous... it's turned into a troll fest in here...

**Comment by ilia2s** [comment]
Working network completely reduce amount of trolls

**Comment by D3m0nKingx** [comment]
It's not like bitcoin itself worked the first time perfectly... clearly they don't remember history well lol

**Comment by John1231983** [comment]
@h4x3rotab : What is future trading? Are they correct that your project was the failure? I have not so much money. It is my money that I saved 5 months

**Comment by mjoh090** [comment]
@StarbuckBG @h4x3rotab As you can see above with @John1231983 situation, there is misunderstanding out there about the difference between futures and actual BTG. On your website in the FAQ you indicate that the BTG can be purchased at exchanges after the hard fork on 25 Oct. A hard fork did not take place on 25 Oct so this is misleading. Secondly, you have not made it clear to that actual BTG cannot be purchased yet until the actual mainnet goes live which you have scheduled for 1 Nov, and that what people are in fact purchasing in the mean time are risky futures. You have a duty of care to clarify this on your website and your channels.

**Comment by h4x3rotab** [comment]
@mjoh090 Sorry for the confusion and thank you for pointing out that. We are going to update the FAQ section.

For more details, please check the roadmap:
https://btcgpu.org/wp-content/uploads/2017/10/BitcoinGold-Roadmap.pdf

And the current development process:
https://bitcoingold.org/bitcoin-gold-dev-update-1/
https://bitcoingold.org/bitcoin-gold-daily-dev-update-26-10-2017/

**Comment by John1231983** [comment]
Thanks. I am trading in the bitfinex. I can buy and sell BTG. After Nov 1, can i still use my BTG or it will lost?

**Comment by mjoh090** [comment]
@John1231983 You don't own any BTG, because you have not bought any BTG. BTG cannot be purchased yet. What you have is a type of contract called a future that derives its value from the sentiment of BTG's future performance. While the value of you investment may have decreased, you have not lost your money. You only lose money when you realise the loss in value of your investment with a sale at a lower price than what you bought it for. The crypto market is highly speculative and therefore very volatile, and consequently can be unpredictable. People that try to convince you one way or the other which way the value of coin will go are often voicing projected hopes that protect their own interest. It is therefore worthwhile seeking out information from a wide range sources, and I would suggest that you pay closer attention to sentiments that are based on argument, rather baseless sentiments.

**Comment by Thecreator1** [comment]
@mjohn090 
You Wrote:
"You only lose money when you realise the loss in value of your investment with a sale at a lower price than what you bought it for. "

This is not totally true, He will also lose his funds when he is dealing with market manipulators, scammers that will manipulate the price feed to steal customers capital.
It happens a lot these day's because it is a relatively easy way to 'make' money.
If this is the case there is no BTG no futures contracts no nothing, just some guy's that are generating the fake price feed and adjusting this feed to make as many people loose as possible.

@John1231983
If you really want to trade BTG i suggest you get your funds back fast, as fast as if you need to escape from a burning house, and then wait until you can fund a wallet so that the transaction gets logged into the new BTG Blockchain, after the Mainnet has been started, if they ever start it
By now it should be clear to you that you are not holding BTG and that there is a rather large chance that your funds will be lost.

**Comment by John1231983** [comment]
Thanks. I sold it 👍
